### ISSUE TITLE
SEToolkit for termux 

### ISSUE THREAD

**Issue by Auxilus** [termux/unstable-packages#81]
Can SET be implemented in termux?

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install setoolkit
```

**Comment by xeffyr** [comment]
Due to the way how `setoolkit` was developed, I'm expecting 10% (or less) of functionality working. Though, if you can improve it - you can always submit a pull request.

For now, functionality related to following things is probably broken:

* apache2: setoolkit relies on sysvinit-like scripts to start/stop daemon.

* dnsspoof: package `dsniff` is not available.

* ettercap: package is not available.

* isc-dhcp-server: package is not available.

* nginx: same as apache2 - setoolkit expects sysvinit-like init system in order to control services.

* sendmail: available for Termux only as busybox applet which is not enough. Also, running globally-visible SMTP server is likely not possible (for regular clients, the 25 port blocked by most ISPs).

* upx: package is not available.
